### ISSUE TITLE
Bookmarked link to an ayah

### ISSUE THREAD

**Issue by abdulloooh** [teezzan/An-Ayah-A-Day#13]
I think each ayah throughout the whole Quran should have distinctive url.
Example `dailyayah.herokuapp.com/id/more/id/if/their/is/any` eg `dailyayah.herokuapp.com/2/100` which will probably imply chapter 2 verse 100.

Benefit:

- Readers can bookmark a particular verse to be checked later
- Readers can share a particular verse with their friends
- Readers can share such link to social media

Previous state:
No identification, anyone that comes get random ayah

Let me know what you think and how soon you can implement this

**Comment by abdulloooh** [comment]
I have figured out sharing to social media. I need this distinctive link feature as clickable link on shared item.
Mind you, it is not shared in form of image but as text-content that will have link to read more

**Comment by teezzan** [comment]
#16 Has a vue-router implementation. as There is no electricity here, I think you shpuld work on the generating part of it.
For now, both `http://localhost:8080/permalink/100/4` and `http://localhost:8080` works very well.

**Comment by teezzan** [comment]
You can tweak `/permalink`  in the `@/route/index.js` file. probably change it to something else.

**Comment by teezzan** [comment]
Also our Home page is no longer `App.vue` but `@/views/Home.vue`. But they contain the same thing

**Comment by teezzan** [comment]
#17 Is a successful merge. Link generation still required TBD

**Comment by teezzan** [comment]
for some reason, I cant find the share by whatsapp thing again

**Comment by teezzan** [comment]
I think I have messed stuff up o. I cant find the commits related to Social media sharing

**Comment by teezzan** [comment]
locally

**Comment by teezzan** [comment]
You have not implemented the button that generates the permalink link of the Ayah. Basic press button, copied to clipboard.

**Comment by abdulloooh** [comment]
I have been busy. My mind is on it, I will in shaa Allah soon

**Comment by abdulloooh** [comment]
done, I am closing this issue for now
