### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by abdulloooh** [teezzan/An-Ayah-A-Day#15]
We need a better english translation probably that of Sahih International that uses pure modern english

**Comment by abdulloooh** [comment]
@teezzan  Not sure you saw this?

**Comment by teezzan** [comment]
Do you have a recommendation? So that we can try to get it and maybe restructure It to look like the one we're currently using. JSON format preferred

**Comment by abdulloooh** [comment]
Mentioned it in the original issue. `Sahih International` is very good, generally acceptable with pure English translation

**Comment by teezzan** [comment]
Looked around. Can't find it. If you can help, please do. Send me  a link.

**Comment by abdulloooh** [comment]
Anyone that you find and you feel it is ok sha. Try `Mushin Khan`. I feel `Sahih International` will be popular tho and has amazing translation if you really wana find it. Else, we can leave it as it currently is

**Comment by teezzan** [comment]
http://api.alquran.cloud/v1/quran/en.sahih

**Comment by teezzan** [comment]
Fixed.. 3 line fix ...
